name: Comment Commands

on:
  issue_comment:
    types: [created]

jobs:
  fix-format:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/format')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container: wpilib/roborio-cross-ubuntu:2023-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.issue.pull_request.head.ref }}

    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run tests on robot code
      run: ./gradlew spotlessApply

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: run spotless
        branch: ${{ github.event.issue.pull_request.head.ref }}
